SELECT DISTINCT crcc.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR crcc
         JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY crch ON crcc.CAR_ID = crch.CAR_ID
WHERE crcc.CAR_TYPE = '세단'
          AND MONTH(crch.START_DATE) = 10
ORDER BY crcc.CAR_ID DESC;