SELECT
    QUARTER,
    COUNT(*) AS ECOLI_COUNT
FROM
    (SELECT
         CONCAT(EXTRACT(QUARTER FROM DIFFERENTIATION_DATE), 'Q') AS QUARTER
     FROM
         ECOLI_DATA) AS QUARTER_DATA
GROUP BY
    QUARTER
ORDER BY
    QUARTER;
