SELECT DISTINCT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS YEAR, COUNT(DISTINCT(OS.USER_ID)) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT(OS.USER_ID))
    /
    (SELECT COUNT(USER_ID) FROM USER_INFO WHERE YEAR(JOINED)=2021), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE AS OS
    JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
    ) AS US ON OS.USER_ID = US.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR(SALES_DATE), MONTH(SALES_DATE)