SELECT
    D.ID,
    D.EMAIL,
    D.FIRST_NAME,
    D.LAST_NAME
FROM
    DEVELOPERS D
        JOIN
    SKILLCODES S1 ON (D.SKILL_CODE & S1.CODE) = S1.CODE
WHERE
    S1.NAME IN ('Python', 'C#')
GROUP BY
    D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
ORDER BY
    D.ID ASC;
