SELECT c.CAR_ID, c.CAR_TYPE, FLOOR(c.DAILY_FEE * 30 * (1 - p.DISCOUNT_RATE / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
         LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE NOT (START_DATE > '2022-11-30' OR END_DATE < '2022-11-01')
) h ON c.CAR_ID = h.CAR_ID
WHERE c.CAR_TYPE IN ('세단', 'SUV') AND h.CAR_ID IS NULL
HAVING FEE BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;